
name: Full CICD Pipeline

on:
    workflow_dispatch: 
      inputs:
        environment:
          description: This is the environment value where this workflow runs
          default: 'dev'
          required: true
          type: choice
          options:
            - dev
            - prod
            - staging

jobs:

    Code:
        runs-on: ubuntu-latest
        steps:
          - name: checkout code from git hub
            run: echo "mvn clean packages"

    Build:
        needs: ["Code"]
        runs-on: ubuntu-latest
        steps:
          - name: Build application
            run: echo "build -t myimage"

    Test:
        needs: ["Code","Build"]
        runs-on: ubuntu-latest
        steps:
          - name: Test application
            run: echo "runnig Test cases"
    deploy:
        if: inputs.environment == 'dev'
        needs: [ "Code","Build","Test" ]

        runs-on: ubuntu-latest
        steps: 
          - name: deploy application
            run: echo "deployed application successfully"




