name: DevSecOps End to End Pipeline

on:
    push:
        branches: [main]

jobs:
    code-quality:
        uses: ./.github/workflows/Code-Quality.yml

    secrets-scan: 
        uses: ./.github/workflows/secrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/Dependency-Scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    build:
        needs: [code-quality,  secrets-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/docker-build-push-scan.yml
        secrets: inherit
    
    Trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit

    